CREATE TABLE T_CUSTOMER
(
    ID           VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '唯一键',
    USER_NAME    VARCHAR(32) NULL COMMENT '用户名',
    GENDER       TINYINT NULL COMMENT '性别 0=未知 1=男 2=女',
    AVATAR_URL   VARCHAR(64) NULL COMMENT '头像地址',
    PHONE_NUMBER VARCHAR(12) NULL COMMENT '电话号码',
    EMAIL        VARCHAR(64) NULL COMMENT '邮箱地址',
    USER_STATUS  TINYINT DEFAULT 0 NULL COMMENT '用户状态 0=正常 1=异常',
    IS_DELETED   TINYINT DEFAULT 0 NULL COMMENT '是否删除',
    CREATED_USER VARCHAR(32) NULL COMMENT '创建人',
    CREATED_TIME TIMESTAMP NULL COMMENT '创建时间',
    UPDATED_USER VARCHAR(32) NULL COMMENT '更新人',
    UPDATED_TIME TIMESTAMP NULL COMMENT '更新时间'
) COMMENT '用户信息表';

CREATE TABLE T_PRODUCT
(
    ID           VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '唯一键',
    TITLE        VARCHAR(64) NOT NULL COMMENT '商品标题',
    DESCRIPTION  VARCHAR(128) NULL COMMENT '商品描述',
    PRICE        DECIMAL(10, 2) NULL COMMENT '单价',
    STOCK        INT     default 0 NULL COMMENT '库存数量',
    STATUS       TINYINT NULL COMMENT '状态 0=已下架 1=上架',
    IS_DELETED   TINYINT DEFAULT 0 NULL COMMENT '是否删除',
    CREATED_USER VARCHAR(32) NULL COMMENT '创建人',
    CREATED_TIME TIMESTAMP NULL COMMENT '创建时间',
    UPDATED_USER VARCHAR(32) NULL COMMENT '更新人',
    UPDATED_TIME TIMESTAMP NULL COMMENT '更新时间'
) COMMENT '商品表';

CREATE TABLE T_PRODUCT_IMAGE
(
    ID            VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '唯一键',
    PRODUCT_ID    VARCHAR(32) NOT NULL COMMENT '商品id',
    IMAGE_URL     VARCHAR(256) NULL COMMENT '图片连接',
    IS_DISPLAY    TINYINT NULL COMMENT '是否为列表展示图片',
    DISPLAY_ORDER INT NULL COMMENT '图片展示顺序',
    IS_DELETED    TINYINT DEFAULT 0 NULL COMMENT '是否删除',
    CREATED_USER  VARCHAR(32) NULL COMMENT '创建人',
    CREATED_TIME  TIMESTAMP NULL COMMENT '创建时间',
    UPDATED_USER  VARCHAR(32) NULL COMMENT '更新人',
    UPDATED_TIME  TIMESTAMP NULL COMMENT '更新时间'
) COMMENT '商品图片表';

CREATE TABLE `T_ORDER`
(
    `ID`               varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '唯一键',
    `CUSTOMER_ID`      varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL COMMENT '客户Id（买家）',
    `ADDRESS_ID`       varchar(32) COLLATE utf8mb4_unicode_ci  DEFAULT NULL,
    `STATUS`           tinyint                                NOT NULL COMMENT '订单状态',
    `TOTAL_PRICE`      decimal(12, 3)                          DEFAULT NULL COMMENT '订单总金额',
    `TOTAL_QUANTITY`   int                                     DEFAULT NULL COMMENT '订单物品总数',
    `REMARK`           varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '订单备注',
    `PAY_TIME`         timestamp NULL DEFAULT NULL,
    `PAY_TYPE`         tinyint                                 DEFAULT NULL,
    `SHIP_TIME`        timestamp NULL DEFAULT NULL,
    `IS_DELETED`       tinyint                                 DEFAULT 0 COMMENT '是否删除',
    `CREATED_USER`     varchar(32) COLLATE utf8mb4_unicode_ci  DEFAULT NULL COMMENT '创建人',
    `CREATED_TIME`     timestamp NULL DEFAULT NULL COMMENT '创建时间',
    `UPDATED_USER`     varchar(32) COLLATE utf8mb4_unicode_ci  DEFAULT NULL COMMENT '更新人',
    `UPDATED_TIME`     timestamp NULL DEFAULT NULL COMMENT '更新时间',
    `RECEIVER_NAME`    varchar(32) COLLATE utf8mb4_unicode_ci  DEFAULT NULL COMMENT '收件人姓名快照',
    `RECEIVER_PHONE`   varchar(20) COLLATE utf8mb4_unicode_ci  DEFAULT NULL COMMENT '收件人电话快照',
    `RECEIVER_ADDRESS` varchar(256) COLLATE utf8mb4_unicode_ci DEFAULT NULL COMMENT '收件人详细地址快照',
    PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='订单表'

CREATE TABLE T_ORDER_PRODUCT
(
    ID                     VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '唯一键',
    PRODUCT_ID             VARCHAR(32) NOT NULL COMMENT '商品ID',
    PRODUCT_NAME_SNAPSHOT  VARCHAR(64) NULL COMMENT '商品标题快照',
    ORDER_ID               VARCHAR(32) NOT NULL COMMENT '订单ID',
    PRODUCT_QUANTITY       INT DEFAULT 1 NULL COMMENT '商品总数',
    PRODUCT_PRICE_SNAPSHOT DECIMAL(10, 2) NULL COMMENT '下单时商品单价',
    IS_DELETED             TINYINT DEFAULT 0 COMMENT '是否删除',
    CREATED_USER           VARCHAR(32) NULL COMMENT '创建人',
    CREATED_TIME           TIMESTAMP NULL COMMENT '创建时间',
    UPDATED_USER           VARCHAR(32) NULL COMMENT '更新人',
    UPDATED_TIME           TIMESTAMP NULL COMMENT '更新时间'
) COMMENT '订单商品关系表';

CREATE TABLE T_ADDRESS
(
    ID             VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '唯一键',
    USER_ID        VARCHAR(32) NOT NULL COMMENT '用户id',
    RECIPIENT_NAME VARCHAR(32) NOT NULL COMMENT '收件人名称',
    PHONE          VARCHAR(12) NOT NULL COMMENT '收件人电话',
    ADDRESS        VARCHAR(256) NULL COMMENT '收件人地址',
    IS_DEFAULT     TINYINT DEFAULT 0 NULL COMMENT '是否为默认地址',
    IS_DELETED     TINYINT DEFAULT 0 NULL COMMENT '是否删除',
    CREATED_USER   VARCHAR(32) NULL COMMENT '创建人',
    CREATED_TIME   TIMESTAMP NULL COMMENT '创建时间',
    UPDATED_USER   VARCHAR(32) NULL COMMENT '更新人',
    UPDATED_TIME   TIMESTAMP NULL COMMENT '更新时间'
) COMMENT '用户地址表';

CREATE TABLE T_SHIPMENT
(
    ID                VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '唯一键',
    ORDER_ID          VARCHAR(32) NOT NULL COMMENT '订单id',
    LOGISTICS_NO      VARCHAR(32) NULL COMMENT '快递单号',
    LOGISTICS_COMPANY VARCHAR(32) NULL COMMENT '物流公司名称',
    SHIP_TIME         TIMESTAMP NULL COMMENT '发货时间',
    STATUS            TINYINT NULL COMMENT '发货状态 0=待发货,1=已发货,2=已签收',
    DELIVERY_TIME     TIMESTAMP NULL COMMENT '签收时间',
    IS_DELETED        TINYINT DEFAULT 0 NULL COMMENT '是否删除',
    CREATED_USER      VARCHAR(32) NULL COMMENT '创建人',
    CREATED_TIME      TIMESTAMP NULL COMMENT '创建时间',
    UPDATED_USER      VARCHAR(32) NULL COMMENT '更新人',
    UPDATED_TIME      TIMESTAMP NULL COMMENT '更新时间'
) COMMENT '发货信息表';

CREATE TABLE T_REFUND
(
    ID            VARCHAR(32) NOT NULL PRIMARY KEY COMMENT '唯一键',
    ORDER_ID      VARCHAR(32) NOT NULL COMMENT '订单id',
    REASON        VARCHAR(256) NULL COMMENT '退货原因',
    STATUS        TINYINT DEFAULT 0 NULL COMMENT '退货状态 0=申请中, 1=已通过, 2=已拒绝, 3=已退款',
    APPLY_TIME    TIMESTAMP NULL COMMENT '申请时间',
    REFUND_AMOUNT DECIMAL(10, 2) NULL COMMENT '退货金额',
    REVIEW_TIME   TIMESTAMP NULL COMMENT '商家审核时间',
    REVIEW_REMARK VARCHAR(256) NULL COMMENT '商家审核备注',
    IS_DELETED    TINYINT DEFAULT 0 NULL COMMENT '是否删除',
    CREATED_USER  VARCHAR(32) NULL COMMENT '创建人',
    CREATED_TIME  TIMESTAMP NULL COMMENT '创建时间',
    UPDATED_USER  VARCHAR(32) NULL COMMENT '更新人',
    UPDATED_TIME  TIMESTAMP NULL COMMENT '更新时间'
) COMMENT '退货信息表';
